version: '3.7'

services:

  sample:
    container_name: cnt-reactjs-app-tasks
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 9091:8081
    environment:
      - CHOKIDAR_USEPOLLING=true